FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /gateway-service ./gateway/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /gateway-service .
EXPOSE 8080
CMD ["./gateway-service"]
