// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/history": {
            "get": {
                "description": "Проксирует запрос к сервису истории.",
                "produces": [
                    "application/json"
                ],
                "summary": "Получить историю",
                "responses": {
                    "200": {
                        "description": "Список записей истории",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/interpolate": {
            "post": {
                "description": "Проксирует запрос к сервису интерполяции для вычисления значения.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Интерполяция данных",
                "responses": {
                    "200": {
                        "description": "Успешное вычисление",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/methods": {
            "get": {
                "description": "Возвращает список поддерживаемых методов интерполяции (linear, lagrange, newton).",
                "produces": [
                    "application/json"
                ],
                "summary": "Список доступных методов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Interpolation API",
	Description:      "API Gateway для учебного проекта по интерполяции.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
