// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://localhost/support",
            "email": "mindlessmuse.666@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/history": {
            "get": {
                "description": "Проксирует запрос к сервису истории.",
                "produces": [
                    "application/json"
                ],
                "summary": "Получить историю",
                "responses": {
                    "200": {
                        "description": "Список записей истории",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.CalculationRecord"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет все записи из базы данных истории.",
                "produces": [
                    "application/json"
                ],
                "summary": "Очистить историю",
                "responses": {
                    "200": {
                        "description": "История успешно очищена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/interpolate": {
            "post": {
                "description": "Проксирует запрос к сервису интерполяции для вычисления значения.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Интерполяция данных",
                "parameters": [
                    {
                        "description": "Параметры интерполяции",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.InterpolateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное вычисление",
                        "schema": {
                            "$ref": "#/definitions/main.InterpolateResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат данных",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/methods": {
            "get": {
                "description": "Возвращает список поддерживаемых методов интерполяции (linear, lagrange, newton).",
                "produces": [
                    "application/json"
                ],
                "summary": "Список доступных методов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.CalculationRecord": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-04-28T18:32:04Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "method": {
                    "type": "string",
                    "example": "linear"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Point"
                    }
                },
                "result": {
                    "type": "number",
                    "example": 1.5
                },
                "target_x": {
                    "type": "number",
                    "example": 1.5
                }
            }
        },
        "main.InterpolateRequest": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string",
                    "example": "linear"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Point"
                    }
                },
                "target_x": {
                    "type": "number",
                    "example": 1.5
                }
            }
        },
        "main.InterpolateResponse": {
            "type": "object",
            "properties": {
                "cached": {
                    "type": "boolean",
                    "example": false
                },
                "curve": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Point"
                    }
                },
                "method": {
                    "type": "string",
                    "example": "linear"
                },
                "result": {
                    "type": "number",
                    "example": 1.5
                }
            }
        },
        "main.Point": {
            "type": "object",
            "properties": {
                "x": {
                    "type": "number",
                    "example": 0
                },
                "y": {
                    "type": "number",
                    "example": 0
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Interpolation API",
	Description:      "API Gateway для учебного проекта по интерполяции.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
